### PR TITLE
Fixed error in Post + Permissions, need integration-tests

### LINKED ISSUE #148: Utskotten trasiga
Får 500 när jag försöker gå in på utskotten
http://fsektionen.se/utskott/kultur

Även med id verkar det vara dött
http://fsektionen.se/utskott/1

### PR DESCRIPTION
**Pull request by davidwessman**
Fixes #148, more integration-test needed. WIP

### CODE REVIEW

**Comment by davidwessman** [comment]
I got stuck with the:
https://github.com/fsek/web/blob/master/spec/features/login_visit_election.rb
far too long. Cannot get it right with the JS-testing, and when I gave up on that I couldn't get it to work like before...

**Comment by henrikssn** [comment]
You need to fix your vim config. Mine is a good start. Never use tabs in your cod.

www.github.com/henrikssn/.vim

**Comment by davidwessman** [comment]
@henrikssn
Yeah, I realized i had written ```noexpandtab```instead of ```expand tab```
Gonna recompile the files.

**Comment by davidwessman** [comment]
@henrikssn 
Do you think that you can look at the JS testing? I could not get it to work, spent far too many hours on it...

**Comment by henrikssn** [comment]
@davidwessman I do not know what to do here, PhantomJS works fine both on my mac, on dirac and on Travis. There are some instructions to follow in the gem. What exactly is not working for you?

https://github.com/colszowka/phantomjs-gem

**Comment by davidwessman** [comment]
I ran into errors with the database, wasn't able to create the resources in the same way.
Or, I ran into errors because of it.

Could you structure up an example?

**Comment by henrikssn** [comment]
Could you make a test case in a new branch of something which should work but doesnt? I'll look at it and help :)

**Comment by davidwessman** [comment]
@henrikssn 
I will create a new branch and we can look at it.
Should we merge this?

**Comment by henrikssn** [comment]
@davidwessman Yes, make the hound happy and then merge

File: spec/controllers/cafe_works_controller_spec.rb [hunk 1]
```diff
@@ -156,11 +157,10 @@
 
     context 'with no user' do
       it 'remove worker' do
-        patch :remove_worker,
-              {
-                  id: cwork_access.to_param,
-                  cafe_work: {access_code: cwork_access.access_code}
-              }
+        patch :remove_worker, {
```
Comment (henrikssn) [inline spec/controllers/cafe_works_controller_spec.rb]: You can line break with \ instead

File: spec/rails_helper.rb [hunk 2]
```diff
@@ -59,14 +55,14 @@
 
   config.include Devise::TestHelpers, type: :controller
 
-  config.before(:suite) do
-    DatabaseCleaner.strategy = :transaction
-    DatabaseCleaner.clean_with(:truncation)
-  end
+  #config.before(:suite) do
+  #  DatabaseCleaner.strategy = :transaction
```
Comment (henrikssn) [inline spec/rails_helper.rb]: Are we not using DatabaseCleaner anymore?

Comment (davidwessman) [inline spec/rails_helper.rb]: I thought this was just repeating everything, since we have:
https://github.com/fsek/web/blob/master/spec/support/database_cleaner.rb

File: config/routes.rb [hunk 3]
```diff
@@ -136,11 +134,11 @@
     resources :elections, path: :val, only: :index do
       collection do
         resources :nominations, controller: 'elections/nominations',
-                  path: :nominera, only: [:create] do
+          path: :nominera, only: [:create] do
           get '', action: :new, on: :collection, as: :new
         end
         resources :candidates, controller: 'elections/candidates',
-                  path: :kandidera, except: [:edit]
+          path: :kandidera, except: [:edit]
```
Comment (davidwessman) [inline config/routes.rb]: @henrikssn 
What about this one?

Comment (henrikssn) [inline config/routes.rb]: Align all literals on `controller:`

Example:
````
foo :name, first: :true,
           second: false,
           third: 42

File: spec/rails_helper.rb (hunk 2 above)
Comment (henrikssn) [inline spec/rails_helper.rb]: I see :+1:

Comment (davidwessman) [inline spec/rails_helper.rb]: I'll remove it completely.

File: spec/controllers/cafe_works_controller_spec.rb (hunk 1 above)
Comment (davidwessman) [inline spec/controllers/cafe_works_controller_spec.rb]: I thought I needed it for the param-hash, turned out I didn't ;)

File: spec/controllers/cafe_works_controller_spec.rb [hunk 4]
```diff
@@ -68,14 +68,16 @@
         end
 
         it 'update worker' do
-          patch :update_worker, {id: cwork_profile.to_param, cafe_work: attributes_for(:assignee, :test)}
+          patch :update_worker,
+            id: cwork_profile.to_param,
```
Comment (davidwessman) [inline spec/controllers/cafe_works_controller_spec.rb]: @henrikssn 
What should we do about these ones?
I either need to change my Vim-config or we should edit Hound.

File: config/routes.rb (hunk 3 above)
Comment (davidwessman) [inline config/routes.rb]: Got any Vim solution for this?

File: spec/controllers/cafe_works_controller_spec.rb [hunk 5]
```diff
@@ -68,14 +70,15 @@
         end
 
         it 'update worker' do
-          patch :update_worker, {id: cwork_profile.to_param, cafe_work: attributes_for(:assignee, :test)}
+          patch :update_worker, id: cwork_profile.to_param,
+            cafe_work: attributes_for(:assignee, :test)
```
Comment (davidwessman) [inline spec/controllers/cafe_works_controller_spec.rb]: @henrikssn @jforberg 
Anyway to fix this with vim-config?

**Comment by davidwessman** [comment]
@fsek/admins 

OK to merge?

**Comment by henrikssn** [comment]
LGTM

Ship it!

**Comment by SirDirac** [comment]
This PR was deployed to Production. Reference: <a href='http://samson.fsektionen.se/projects/web/deploys/94' target='_blank'>cdff1a2</a>
